# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirt', 'tshirt'), ('jeans', 'jeans')], max_length=30, null=True),
        ),
    ]
