# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushapp', '0003_auto_20181126_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('tshirt', 'tshirt'), ('jeans', 'jeans')], max_length=60, null=True),
        ),
    ]
